//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long id { get; set; }
        public string usertoken { get; set; }
        public Nullable<int> idnews { get; set; }
        public string contents { get; set; }
        public System.DateTime datetime { get; set; }
        public int datetimeid { get; set; }
        public Nullable<int> replyid { get; set; }
        public string usertokenreplyid { get; set; }
        public string fullName { get; set; }
        public string fullNameReply { get; set; }
    }
}
