//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class content
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string des { get; set; }
        public string image { get; set; }
        public string fullcontent { get; set; }
        public int catid { get; set; }
        public System.DateTime datetime { get; set; }
        public int views { get; set; }
        public string tags { get; set; }
        public int comments { get; set; }
    }
}
