//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dailykeyword
    {
        public int id { get; set; }
        public string keyword { get; set; }
        public string title { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> datetimeid { get; set; }
        public Nullable<byte> active { get; set; }
    }
}
