//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public int id { get; set; }
        public string userToken { get; set; }
        public string email { get; set; }
        public string fullName { get; set; }
        public string link { get; set; }
        public string avatar { get; set; }
        public string idOA { get; set; }
        public string type { get; set; }
    }
}
