//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rss
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<int> catid { get; set; }
        public Nullable<int> domain { get; set; }
        public Nullable<int> parentcatid { get; set; }
        public Nullable<int> groupid { get; set; }
    }
}
