//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class timelineEntities : DbContext
    {
        public timelineEntities()
            : base("name=timelineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cat> cats { get; set; }
        public DbSet<content> contents { get; set; }
        public DbSet<videogiaitri> videogiaitris { get; set; }
        public DbSet<zadv> zadvs { get; set; }
        public DbSet<zalexa> zalexas { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<dailykeyword> dailykeywords { get; set; }
        public DbSet<domain> domains { get; set; }
        public DbSet<filterkeyword> filterkeywords { get; set; }
        public DbSet<hotkeyword> hotkeywords { get; set; }
        public DbSet<like> likes { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<rss> rsses { get; set; }
        public DbSet<test> tests { get; set; }
        public DbSet<title> titles { get; set; }
        public DbSet<titlesSearch> titlesSearches { get; set; }
        public DbSet<userFilter> userFilters { get; set; }
        public DbSet<blockurl> blockurls { get; set; }
        public DbSet<user> users { get; set; }
    }
}
