//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class videogiaitri
    {
        public int id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public string domain { get; set; }
        public string fullContent { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> dateid { get; set; }
    }
}
