//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zadv
    {
        public int id { get; set; }
        public string title { get; set; }
        public string des { get; set; }
        public string filepath { get; set; }
        public byte filetype { get; set; }
        public string link { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string size { get; set; }
        public string cat { get; set; }
    }
}
