//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youknow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zalexa
    {
        public int id { get; set; }
        public string site { get; set; }
        public string keyword { get; set; }
        public string des { get; set; }
        public Nullable<int> rank { get; set; }
    }
}
